apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: eurekaserver
  name: eurekaserver
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: eurekaserver
    spec:
      containers:
      - image: spring-cloud-eurekasvr
        name: eurekaserver
        ports:
        - containerPort: 8761
        resources: {}
      restartPolicy: Always
status: {}
