apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: organizationservice2
  name: organizationservice2
spec:
  ports:
  - name: "8086"
    port: 8086
    targetPort: 8086
  selector:
    io.kompose.service: organizationservice2
status:
  loadBalancer: {}
